### ISSUE TITLE
Exit with zero value when run with `fix` option

### ISSUE THREAD

**Issue by chadr123** [4meepo/tagalign#2]
Currently, the `tagalign` exits with non-zero value when run it with `fix` option if there are things to fix. What about add an option to exit with zero value even if there are things to fix?

I'm using the `tagalign` in a Makefile target that contains several commands including `tagalign` but it fails as `tagalign` exits with non-zero value if there are things to fix. I would like to run subsequent commands after the `tagalign` calling.

WDYT?

**Comment by 4meepo** [comment]
I think the `tagalign` should return with `code: 0` whether there are things to fix or not.

Will fix it ASAP.

**Comment by 4meepo** [comment]
I looked into the source code, seems like I can't control the exit code, please see [here](https://cs.opensource.google/go/x/tools/+/master:go/analysis/internal/checker/checker.go;l=579).

There is a workaround to ignore the exit code, try this

```bash
tagalign -fix  ./... || true   
```

The exit coe will always be 0.

**Comment by chadr123** [comment]
Thanks for your quick response. :) OK. I will try your suggestion. 👍
