### ISSUE TITLE
Better alignment across tags

### ISSUE THREAD

**Issue by mitar** [4meepo/tagalign#3]
So I have tags to configure [kong](https://github.com/alecthomas/kong) and currently this linter formats it as:

```
type File struct {
	Path  string        `help:"Append logs to a file (as well)." json:"path"                        placeholder:"PATH"                                                                                                                                    type:"path"  yaml:"path"`
	Level zerolog.Level `default:"${defaultLoggingFileLevel}"    enum:"trace,debug,info,warn,error" help:"All logs with a level greater than or equal to this level will be written to the file. Possible: ${enum}. Default: ${defaultLoggingFileLevel}." json:"level" placeholder:"LEVEL" yaml:"level"`
}
```

Instead, I would prefer:

```
type File struct {
	Path  string        `                                                                        help:"Append logs to a file (as well)."                                                                                                               json:"path"  placeholder:"PATH"  type:"path" yaml:"path"`
	Level zerolog.Level `default:"${defaultLoggingFileLevel}" enum:"trace,debug,info,warn,error" help:"All logs with a level greater than or equal to this level will be written to the file. Possible: ${enum}. Default: ${defaultLoggingFileLevel}." json:"level" placeholder:"LEVEL"             yaml:"level"`
}
```

So that alignment happens based on shared tags inside a struct.

**Comment by 4meepo** [comment]
Nice suggestion, accepted.

Checkout the v1.3.0, the new feature `strict style` has been added into `tagalign`.

As for `golangci-lint`, it will take more time.

**Comment by mitar** [comment]
Superb! This was fast. I tested it on my code and it works perfectly. Thanks!

**Comment by mitar** [comment]
What is the process to get golangci-lint updated?

**Comment by 4meepo** [comment]
[Tagalign can be configured as a linter](https://golangci-lint.run/usage/linters/#tagalign) in `golangci-lint`.

You can use `golangci-lint` instead of running `tagalign`.

If I want to update the `tagalign` version in `golangci-lint`, I need to create a new PR to the `golangci-lint` codebase. And it will be available after their next minor release. It will take at least 1 month.

**Comment by mitar** [comment]
> I need to create a new PR to the golangci-lint codebase.

Please do so if you are able! :-)

**Comment by 4meepo** [comment]
> > I need to create a new PR to the golangci-lint codebase.
> 
> Please do so if you are able! :-)

Will do.

**Comment by 4meepo** [comment]
Thanks to the `golangci-lint` team. They already did that. 

https://github.com/golangci/golangci-lint/commit/ffe688c24b0726aa39882ea5cbcd8d3335d3588d

**Comment by mitar** [comment]
Awesome!
