### ISSUE TITLE
Tagalign fixes alignment, but doesn't unfix where appropriate

### ISSUE THREAD

**Issue by brandur** [4meepo/tagalign#4]
A common problem we run into with Tagalign is that someone will be working on a new feature, and in the beginning write a simple struct with no documentation, which Tagalign will align the tags of. For example:

``` go
type BatchMeterUsageCreateRequest struct {
	Dimension          string    `json:"dimension"          validate:"required"`
	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`
	PlanID             string    `json:"planId"             validate:"required"`
}
```

But then later, as the feature is finished up, the developer will add documentation to struct members. Gofmt fixes the whitespace that'd been aligning properties, but the tag alignment is now way out of whack:

``` go
type BatchMeterUsageCreateRequest struct {
	// The billing dimension of the batch.
	Dimension string `json:"dimension"          validate:"required"`

	// The effect start time of the batch.
	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`

	// The plan ID of the batch.
	PlanID string `json:"planId"             validate:"required"`
}
```

Tagalign should probably be able to fix alignment problems like this that were created by Tagalign during its original fix.

**Comment by 4meepo** [comment]
Like your said, this is the behavior of `gofmt`.  `gofmt` will always overwrite the result of `tagalign`.

If your expected result is 
```go
type BatchMeterUsageCreateRequest struct {
        // The billing dimension of the batch.
        Dimension string             `json:"dimension"          validate:"required"`

        // The effect start time of the batch.
        EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`

        // The plan ID of the batch.
        PlanID string                `json:"planId"             validate:"required"`
}
```
Then sorry, as far as I know, there's no way to achieve that.

But there is a workaround to add simple documentation and align tags in the same time. Try this
```go
type BatchMeterUsageCreateRequest struct {
	Dimension          string    `json:"dimension"          validate:"required"` // The billing dimension of the batch.
	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"` // The effect start time of the batch.
	PlanID             string    `json:"planId"             validate:"required"` // The plan ID of the batch.
}
```

**Comment by brandur** [comment]
@4meepo Thanks. Let me take a step back and clarify expected behavior.

If we start with this:

``` go
type BatchMeterUsageCreateRequest struct {
	Dimension          string    `json:"dimension" validate:"required"`
	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`
	PlanID             string    `json:"planId" validate:"required"`
}
```

Then run Tagalign, it'll correct to this:

``` go
type BatchMeterUsageCreateRequest struct {
	Dimension          string    `json:"dimension"          validate:"required"`
	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`
	PlanID             string    `json:"planId"             validate:"required"`
}
```

Then say we add docblocks over comments, and end up with this:

``` go
type BatchMeterUsageCreateRequest struct {
	// The billing dimension of the batch.
	Dimension string `json:"dimension"          validate:"required"`

	// The effect start time of the batch.
	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`

	// The plan ID of the batch.
	PlanID string `json:"planId"             validate:"required"`
}
```

If we run Tagalign again, it should _undo_ the original alignment and take us back to this:

``` go
type BatchMeterUsageCreateRequest struct {
	// The billing dimension of the batch.
	Dimension string `json:"dimension" validate:"required"`

	// The effect start time of the batch.
	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`

	// The plan ID of the batch.
	PlanID string `json:"planId" validate:"required"`
}
```

The rationale is that since Tagalign created the alignment problem, it should also be able to fix the problem. Just like Gofmt's alignments, although aligned tags are somewhat desireable when properties are right next to each other, there shouldn't be alignment when they're not.

> But there is a workaround to add simple documentation and align tags in the same time. Try this

Oh yeah, thanks. I know this is possible, and although I used short docstrings in the examples above, many of our docblocks are long, multi-line comments and need to be given their own full block.

**Comment by 4meepo** [comment]
Oh, I see, working on it.

**Comment by brandur** [comment]
Thanks @4meepo!

**Comment by 4meepo** [comment]
> ```go
> type BatchMeterUsageCreateRequest struct {
> 	// The billing dimension of the batch.
> 	Dimension string `json:"dimension"          validate:"required"`
> 
> 	// The effect start time of the batch.
> 	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`
> 
> 	// The plan ID of the batch.
> 	PlanID string `json:"planId"             validate:"required"`
> }
> ```
> 
> If we run Tagalign again, it should _undo_ the original alignment and take us back to this:
> 
> ```go
> type BatchMeterUsageCreateRequest struct {
> 	// The billing dimension of the batch.
> 	Dimension string `json:"dimension" validate:"required"`
> 
> 	// The effect start time of the batch.
> 	EffectiveStartTime time.Time `json:"effectiveStartTime" validate:"required"`
> 
> 	// The plan ID of the batch.
> 	PlanID string `json:"planId" validate:"required"`
> }
> ```

Now it's the `tagalign`'s default behavior. Try the new version v1.3.1.

The `tagalign` linter of `golangci-lint` will be updated soon, too.

**Comment by brandur** [comment]
Nice!! We're using Tagalign through golangci-lint, but looking forward to the next release. Thanks!

**Comment by 4meepo** [comment]
Thanks to the `golangci-lint` team. The version of `tagalign` has been [bumped to `v1.3.1`](https://github.com/golangci/golangci-lint/commit/ffe688c24b0726aa39882ea5cbcd8d3335d3588d).

New feature will be available in their next release.
