### ISSUE TITLE
panic during tags processing

### ISSUE THREAD

**Issue by AlexeyRyabichev** [4meepo/tagalign#6]
At the Process method iteration is done over the `fields` slice, [but `tags` variable is being assigned to the `tagsGroup` slice element](https://github.com/4meepo/tagalign/blob/main/tagalign.go#L275) with an index which can be out of range. This happens in the case when the tags contain a typo.

For example, this code would fail with panic:
```go
package config

type Config struct {
	Host string `envconfig:"HOST" required:"true"`
	Port string `envconfig:"PORT" required:"true`
}
```

```go
panic: runtime error: index out of range [1] with length 1
```

**Comment by 4meepo** [comment]
Are you using `tagalign` binary in standalone mode?  If so, then I can feel you.

`tagalign` should check if the  tags syntax are correct and provide more specific error messages when errors are detected, rather than panic.

Will fix it.

**Comment by AlexeyRyabichev** [comment]
I use it with the `gitlabci-lint`, but since `tagalign` fails with panic, `gitlabci-lint` cannot handle it well

Thanks for looking into that!

**Comment by 4meepo** [comment]
In most cases, the [structtag](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/structtag) analyzer will report these syntax issues in development stage.

Anyway, I'll see what `tagalign` can do.

**Comment by mitar** [comment]
I was just hit by this.
