### ISSUE TITLE
Linter fails to align tags

### ISSUE THREAD

**Issue by mitar** [4meepo/tagalign#9]
I am unable to get tags to be aligned [in this file](https://gitlab.com/tozd/waf/-/blob/main/_examples/hello.go?ref_type=heads#L29-33):

```go
type App struct {
	Config          cli.ConfigFlag `help:"Load configuration from a JSON or YAML file." name:"config"  placeholder:"PATH" short:"c" yaml:"-"`
	z.LoggingConfig `yaml:",inline"`
	Server          waf.Server[*Site] `embed:""                                            yaml:",inline"`
}
```

This is the output after linting. :-(

I am using golangci-lint 1.55.2.

**Comment by mitar** [comment]
My mistake. golangci-lint was not picking up my configuration.

**Comment by mitar** [comment]
OK, there is still something strange going on.

**Comment by 4meepo** [comment]
There is a unexpected embedding field `z.LoggingConfig`, I'll look into it.

**Comment by 4meepo** [comment]
I created a example code and align it manually. 

```bash
cat foobar.go
```
```text
❯ 
package main

import "io"

type FooBar struct {
        Foor      string `yaml:"-"       help:"Load configuration from a JSON or YAML file." name:"config" placeholder:"PATH" short:"c"`
        io.Writer        `yaml:",inline"`
        Bar       string `yaml:",inline" embed:""`
}
```go

❯ gofmt -d foobar.go
diff foobar.go.orig foobar.go
--- foobar.go.orig
+++ foobar.go
@@ -4,6 +4,6 @@
 
 type FooBar struct {
        Foor      string `yaml:"-"       help:"Load configuration from a JSON or YAML file." name:"config" placeholder:"PATH" short:"c"`
-       io.Writer        `yaml:",inline"`
+       io.Writer `yaml:",inline"`
        Bar       string `yaml:",inline" embed:""`
 }
```

**Comment by mitar** [comment]
I see. Thank you for figuring this out.

**Comment by mitar** [comment]
I am still unable to get golangci-lint to run on this example file when I run it from the top directory. I even added:

```
run:
  skip-dirs: []
  skip-dirs-use-default: false
```

To my .golangci.yml file, but it still does not run. I have to run it inside `_examples` directory that it works. Is it possible that this linter suffers from https://github.com/golangci/golangci-lint/issues/913 ?

**Comment by mitar** [comment]
> So, I recommend you change you code to this style:

The issue with that is that the order of fields in my case matters, because [Kong](https://github.com/alecthomas/kong) which I use for CLI parsing formats help usage output based on order of fields in a struct.

It is not critical, but I wanted `--config` to be first, before `--logging` section.

**Comment by 4meepo** [comment]
Check out the `golangci-lint` configuration.

<img width="1136" alt="image" src="https://github.com/4meepo/tagalign/assets/28745416/e09f9977-3adf-43b2-9f01-4ebb17c9cb2b">

**Comment by 4meepo** [comment]
It's very werid, I cloned your repo and tried to run linter.  And added

```yaml
linters-settings:
  skip-dirs-use-default: false
```

to the `.golangci.yaml` file, but it didn't work.

And I ran this in the terminal, it worked

```bash
golangci-lint run ./... --fast --fix -v --skip-dirs-use-default=false
```

I think maybe it's a bug from `golangci-lint`.

**Comment by mitar** [comment]
```
linters-settings:
  skip-dirs-use-default: false
```

My understanding is, that it should be:

```
run:
  skip-dirs-use-default: false
```

I tried:

```
golangci-lint run --timeout 4m --color always --allow-parallel-runners --fix --skip-dirs-use-default=false -v
```

And it didn't help. I do not have `./...` in there?

**Comment by mitar** [comment]
Running `golangci-lint run ./... --fast --fix -v --skip-dirs-use-default=false` from top of the repository does not fix the file for me.
